(setenv "PAGER" "cat")
(setq inhibit-splash-screen t)
(setq standard-indent 4)
(setq-default indent-tabs-mode nil)
(line-number-mode 1)
(column-number-mode 1)
(setq-default fill-column 72)
(setq auto-fill-mode 1)
(setq default-major-mode 'text-mode)
(global-font-lock-mode 1)
(set-default-font "DejaVu Sans Mono-10")
(set-background-color "black")
(set-foreground-color "darkkhaki")
;(set-cursor-color "grey")
(global-hl-line-mode 1)
(set-face-background 'hl-line "grey18")
;(set-face-foreground 'hl-line "grey85")
(mouse-wheel-mode t)
(tool-bar-mode -1)
(set-scroll-bar-mode 'right)
