" ~/.gvimrc ~/.vim/gvimrc
" Author: Raghu V. Rao <raghu.v.rao@gmail.com>

set mouse=a

set showtabline=2

" Use the native/non-GUI tab line.
set guioptions-=e

" Enable the horizontal scrollbar.
set guioptions+=b

" Adjust the horizontal scrollbar thumb size to match the cursor-line,
" and not the longest visible line (reduces computations).
set guioptions+=h

" Remove the toolbar from view.
set guioptions-=T

" Use console dialogs instead of pop-up dialogs for simple questions.
set guioptions+=c
