" ~/.gvimrc ~/.vim/gvimrc
" Author: Raghu V. Rao <raghu.v.rao@gmail.com>

set mouse=a

" Use native/non-GUI tab line.
set guioptions-=e

" Left-side scrollbars always off.
set guioptions-=L guioptions-=l

" Horizontal and right-side scroll bars always on.
set guioptions+=b guioptions+=R guioptions+=r

" Horizontal scrollbar length applies to cursor-line only, and not longest
" line in view.
set guioptions+=h

" Exclude toolbar.
set guioptions-=T

" Console dialogs instead of pop-up dialogs for simple questions.
set guioptions+=c
