#!/usr/bin/perl
# Toggle fullscreen
#
# URxvt.perl-ext-common: fullscreen
# URxvt.keysym.F11: perl:fullscreen:toggle

sub on_action {
    my ($self, $action) = @_;
    if ($action eq "toggle") {
        my $dummy = `wmctrl -r :ACTIVE: -b toggle,fullscreen` ;
    }
    ()
}
